-- NextStock - referencia historica para public.branches.
--
-- Este arquivo nao aplica schema.
-- Fluxo principal: rode as migrations Prisma com:
--
--   npm run db:migrate
--
-- A migration oficial correspondente fica em:
--
--   prisma/migrations/20260526000000_add_branch_is_active/migration.sql
--
-- Qualquer nova alteracao estrutural de banco deve ser criada em
-- prisma/migrations, nao neste arquivo.
