-- NextStock - referencia historica para Supabase Auth "Database error creating new user".
--
-- Este arquivo nao aplica schema.
-- Fluxo principal: rode as migrations Prisma com:
--
--   npm run db:migrate
--
-- A migration oficial correspondente fica em:
--
--   prisma/migrations/20260527000000_remove_supabase_profile_trigger/migration.sql
--
-- Qualquer nova alteracao estrutural de banco deve ser criada em
-- prisma/migrations, nao neste arquivo.
